### PR TITLE
Add subgraph to Peggo

### LINKED ISSUE #41: Create Peggy Subgraph
The current bridge UI is rather simple and does not provide users any visual indication of the progress of one's transfers. 

We can use The Graph as a general purpose backend API for use by client-facing services as well as internal monitoring/alerting. 

## [injective-station](https://github.com/InjectiveLabs/injective-station)
The station (and possibly also DEX) can use this API to show historical cross-chain deposits/withdrawals as well as real-time estimates for pending deposits. 

- [x] obtaining historical ERC-20 deposits from Ethereum -> Injective (by scanning [`SendToCosmosEvent`](https://github.com/InjectiveLabs/peggo/blob/dd5760bce0a82cb241a7c00cc218ef2978f0420c/solidity/contracts/Peggy.sol#L440))
- [x] obtaining a historical ERC-20 withdrawals from Injective -> Ethereum (by using [CallHandlers](https://thegraph.com/docs/developer/create-subgraph-hosted#call-handlers) on the [`submitBatch`](https://github.com/InjectiveLabs/peggo/blob/dd5760bce0a82cb241a7c00cc218ef2978f0420c/solidity/contracts/Peggy.sol#L324))

## internal monitoring
Although this won't be used by any mission critical services, having this nice GraphQL API can easily allow us to make sure Peggy is functioning properly. With this API, we can create monitoring bots or even a future analytics site which uses this API as well. 

- [x] tracking the last updated Validator set & powers (also by using CallHandlers on the [`updateValset`](https://github.com/InjectiveLabs/peggo/blob/dd5760bce0a82cb241a7c00cc218ef2978f0420c/solidity/contracts/Peggy.sol#L239) function)
- [x] tracking all of the Deployed ERC-20's (by scanning [`ERC20DeployedEvent`](https://github.com/InjectiveLabs/peggo/blob/dd5760bce0a82cb241a7c00cc218ef2978f0420c/solidity/contracts/Peggy.sol#L461))
- [ ] tracking the up-to-date state variables for convenience 

### Implementation Checklist 
- [x] Define GraphQL Schema
- [x] Implement event and call handler mappings
- [ ] Deploy on The Graph's hosted Ethereum Subgraph service

### PR DESCRIPTION
**Pull request by gorgos**
Fixes #41

### CODE REVIEW

**Comment by albertchon** [comment]
Let's change the current `Withdrawal` to `BatchWithdrawal` and also adding a separate user-specific `Withdrawal` which is 
```graphql
type Withdrawal @entity {
  id: ID!
  tokenContract: Bytes!
  destination: Bytes!
  fee: BigInt!
  amount: BigInt!
  timestamp: BigInt!
  blockHeight: Int64!
}
```
This way the FE can query the Withdrawal API for a single user. 
Let's add timestamp and blockHeight to each of the schema. 

Also, for the `BatchWithdrawal`, I think it's worth also tracking the msg.sender as well as the `totalFee` which is sum(fees).

**Comment by albertchon** [comment]
Also, for the `destination` can we change this to `String` and use the bech32 inj address? @gorgos

**Comment by gorgos** [comment]
> Also, question on the call handler: does The Graph skips transactions that are reverted? If it doesn't, we should skip it

Yes it definitely should skip those.

**Comment by albertchon** [comment]
Btw @bangjelkoski we can just query The Graph by having the client convert the INJ address to the required bytes format right?, so I don't think we'll need to convert the `destination` address to INJ form @gorgos 

e.g. `0x0000000000000000000000009bc909a386a043bbb30fe1aad3fe1f06d8c4f8df` is just the users's Ethereum address but with 24 leading 0's (12 bytes). 
image

- Mainnet: https://thegraph.com/legacy-explorer/subgraph/gorgos/injectivepeggo?selected=playground
- Kovan: https://thegraph.com/legacy-explorer/subgraph/gorgos/injective-peggo-kovan?selected=playground

**Comment by bangjelkoski** [comment]
> Btw @bangjelkoski we can just query The Graph by having the client convert the INJ address to the required bytes format right?, so I don't think we'll need to convert the `destination` address to INJ form @gorgos
> 
> e.g. `0x0000000000000000000000009bc909a386a043bbb30fe1aad3fe1f06d8c4f8df` is just the users's Ethereum address but with 24 leading 0's (12 bytes).
> image
> 
> * Mainnet: https://thegraph.com/legacy-explorer/subgraph/gorgos/injectivepeggo?selected=playground
> * Kovan: https://thegraph.com/legacy-explorer/subgraph/gorgos/injective-peggo-kovan?selected=playground

Yes, we can - easily. The only "issue" I see here is that this has to be documented properly if someone else wants to access this data.

**Comment by gorgos** [comment]
> Btw @bangjelkoski we can just query The Graph by having the client convert the INJ address to the required bytes format. So we don't actually to convert the destination address to INJ-prefixed Bech32 form @gorgos

Yes I was going to suggest this also as it's not trivial to do in AssemblyScript.

**Pull request merged**
